version: "3.8"

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
    environment:
      - QDRANT__SERVER__LISTEN__ADDRESS=0.0.0.0:6333
    volumes:
      - qdrant_storage:/qdrant/storage
    networks:
      - qdrant_network

volumes:
  qdrant_storage:

networks:
  qdrant_network:
    driver: bridge
