version: "3.8"

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
    environment:
      - QDRANT__SERVER__LISTEN__ADDRESS=0.0.0.0:6333
    volumes:
      - qdrant_storage:/qdrant/storage
    networks:
      - qdrant_network

  qdrant-ui:
    image: qdrant/qdrant-ui:latest
    container_name: qdrant-ui
    ports:
      - "3000:3000"
    environment:
      - QDRANT_API_URL=http://qdrant:6333  # Conecta ao serviço qdrant
    networks:
      - qdrant_network

volumes:
  qdrant_storage:

networks:
  qdrant_network:
    driver: bridge
